### PR TITLE
Task 4

### PR DESCRIPTION
**Pull request by monuelDePari**

### CODE REVIEW

**Review by polyakovartem — CHANGES_REQUESTED** [review]
where is wraps implementation?

**Comment by monuelDePari** [comment]
In task4 where I hash

вт, 15 жовт. 2019 о 11:36 Artem <notifications@github.com> пише:

**Comment by monuelDePari** [comment]
Ah I see, I’ll fix it

вт, 15 жовт. 2019 о 12:06 Roman Lynnyk <roman.lynnyk.sa@gmail.com> пише:

**Review by polyakovartem — CHANGES_REQUESTED** [review]
it must be your own wraps implementation, not usage

**Comment by monuelDePari** [comment]
👌

вт, 15 жовт. 2019 о 12:10 Artem <notifications@github.com> пише:

**Pull request closed without merging**
